import { IAlcohol } from "../types/ICommon";

export const productList: IAlcohol[] = [
  {
    id: "sdsds2233der",
    name: "Lanson",
    price: 450,
    category: "rum",
    description: "test",
    image:
      "https://th.bing.com/th/id/R.0263297fa2fb678a63580665e519ca95?rik=NyuHmHTnsA7vjQ&riu=http%3a%2f%2fwww.pngpix.com%2fwp-content%2fuploads%2f2016%2f08%2fPNGPIX-COM-Wine-Bottle-PNG-Transparent-Image-2.png&ehk=AGF2OIB1DlvzNBOB43%2fIu9F7gfOXsiS9qWfrfAHyfyc%3d&risl=&pid=ImgRaw&r=0",
    rating: 4,
    color: "orange-500",
    metaData: [{ volume: "100" }, { alcohol: 8.5 }],
    inStock: true,
  },
  {
    id: "sdsds2ww233d0394er",
    name: "St Da Squad",
    price: 450,
    category: "beer",
    description: "test",
    image: "https://freepngimg.com/thumb/bottle/67-beer-bottle-png-image.png",
    rating: 4,
    color: "green-600",
    metaData: [{ volume: "100" }, { alcohol: 8.5 }],
    inStock: true,
  },
  {
    id: "sdsds2ww233d0394sder",
    name: "St Da Squad",
    price: 450,
    category: "rum",
    description: "test",
    image: "https://freepngimg.com/thumb/bottle/67-beer-bottle-png-image.png",
    rating: 4,
    color: "green-600",
    metaData: [{ volume: "100" }, { alcohol: 8.5 }],
    inStock: true,
  },
  {
    id: "sdsdsdwwedr",
    name: "Lanson",
    price: 150,
    category: "whisky",
    description: "test",
    image:
      "https://th.bing.com/th/id/R.1ad7e1fe51c6e7960f123d7a337a45b3?rik=JUE1%2fQ6XkGbH6A&riu=http%3a%2f%2fassets.stickpng.com%2fimages%2f585e7378cb11b227491c344b.png&ehk=80NMIQ%2frDLPiN2UR3rl8MutvpF43GGZ4tTaCbTjFbsY%3d&risl=&pid=ImgRaw&r=0",
    rating: 4,
    color: "green-600",
    metaData: [{ volume: "100" }, { alcohol: 8.5 }],
    inStock: true,
  },
  {
    id: "233ww3",
    name: "San Miguel",
    price: 150,
    category: "wine",
    description: "test",
    image: "https://webstockreview.net/images/beer-bottle-png-9.png",
    rating: 4,
    color: "orange-500",
    metaData: [{ volume: "100" }, { alcohol: 8.5 }],
    inStock: true,
  },
  {
    id: "233ww2www233",
    name: "Paper Cups",
    price: 5,
    category: "glass",
    description: "test",
    image:
      "https://cdn.cliqueinc.com/cache/posts/img/uploads/current/images/0/252/879/main.original.600x0c.jpg?interlace=true&quality=70",
    rating: 4,
    color: "orange-500",
    metaData: [{ volume: "100" }, { alcohol: 8.5 }],
    inStock: true,
  },
  {
    id: "233ww2www23eee3",
    name: "Classic Lays",
    price: 5,
    category: "snacks",
    description: "test",
    image:
      "https://i.pinimg.com/originals/46/35/7b/46357bb8d375d78ca109c5a46424f9e2.jpg",
    rating: 4,
    color: "orange-500",
    metaData: [{ Weight: "50gm" }],
    inStock: true,
  },
  {
    id: "233ww2wwerrw233",
    name: "Kurkure Masala Munch",
    price: 5,
    category: "snacks",
    description: "test",
    image:
      "https://d2vgqt3b164gwy.cloudfront.net/public/thumbs/products/1305/kurkure_(1)_300_300.jpg",
    rating: 4,
    color: "orange-500",
    metaData: [{ volume: "100" }, { alcohol: 8.5 }],
    inStock: true,
  },
  {
    id: "233ww2233",
    name: "Plastic Glass",
    price: 3,
    category: "glass",
    description: "test",
    image: "https://celebration.co.uk/wp-content/uploads/R280Y.jpg",
    rating: 4,
    color: "orange-500",
    metaData: [{ volume: "100" }, { alcohol: 8.5 }],
    inStock: true,
  },
  {
    id: "2333",
    name: "San Miguel",
    price: 150,
    category: "beer",
    description: "test",
    image: "https://webstockreview.net/images/beer-bottle-png-9.png",
    rating: 4,
    color: "orange-500",
    metaData: [{ volume: "100" }, { alcohol: "8.5%" }],
    inStock: true,
  },
  {
    id: "23kkkksd33",
    name: "San Miguel",
    price: 150,
    category: "beer",
    description: "test",
    image: "https://webstockreview.net/images/beer-bottle-png-9.png",
    rating: 4,
    color: "orange-500",
    metaData: [{ volume: "100" }, { alcohol: "8.5%" }],
    inStock: true,
  },
  {
    id: "2333eewewew",
    name: "San Miguel",
    price: 150,
    category: "beer",
    description: "test",
    image: "https://webstockreview.net/images/beer-bottle-png-9.png",
    rating: 4,
    color: "orange-500",
    metaData: [{ volume: "100" }, { alcohol: "8.5%" }],
    inStock: true,
  },
  {
    id: "2qqq333",
    name: "San Miguel",
    price: 150,
    category: "beer",
    description: "test",
    image: "https://webstockreview.net/images/beer-bottle-png-9.png",
    rating: 4,
    color: "orange-500",
    metaData: [{ volume: "100" }, { alcohol: "8.5%" }],
    inStock: true,
  },
  {
    id: "23w33",
    name: "San Miguel",
    price: 150,
    category: "beer",
    description: "test",
    image: "https://webstockreview.net/images/beer-bottle-png-9.png",
    rating: 4,
    color: "orange-500",
    metaData: [{ volume: "100" }, { alcohol: "8.5%" }],
    inStock: true,
  },
  {
    id: "233w3",
    name: "San Miguel",
    price: 150,
    category: "beer",
    description: "test",
    image: "https://webstockreview.net/images/beer-bottle-png-9.png",
    rating: 4,
    color: "orange-500",
    metaData: [{ volume: "100" }, { alcohol: "8.5%" }],
    inStock: true,
  },
  {
    id: "23323333",
    name: "Malboro",
    price: 150,
    category: "cigarettes",
    description: "test",
    image:
      "https://i.pinimg.com/originals/2b/7a/20/2b7a20687bf7bbc12b7f8532d0db5930.png",
    rating: 4,
    color: "orange-500",
    metaData: [{ quantity: "1 PACK", size: "12" }],
    inStock: true,
  },
  {
    id: "2332333ksldsddd3",
    name: "Malboro",
    price: 150,
    category: "cigarettes",
    description: "test",
    image:
      "https://i.pinimg.com/originals/2b/7a/20/2b7a20687bf7bbc12b7f8532d0db5930.png",
    rating: 4,
    color: "orange-500",
    metaData: [{ quantity: "1 PACK", size: "12" }],
    inStock: false,
  },
];
