import { IAlcohol } from "../types/ICommon";

export const productList: IAlcohol[] = [
  {
    id: "sdsds2233der",
    name: "Lanson",
    price: 450,
    category: "rum",
    description: "test",
    image:
      "https://th.bing.com/th/id/R.0263297fa2fb678a63580665e519ca95?rik=NyuHmHTnsA7vjQ&riu=http%3a%2f%2fwww.pngpix.com%2fwp-content%2fuploads%2f2016%2f08%2fPNGPIX-COM-Wine-Bottle-PNG-Transparent-Image-2.png&ehk=AGF2OIB1DlvzNBOB43%2fIu9F7gfOXsiS9qWfrfAHyfyc%3d&risl=&pid=ImgRaw&r=0",
    rating: 4,
    color: "orange-500",
    metaData: [{ volume: "100" }, { alcohol: 8.5 }],
    inStock: true,
  },
  {
    id: "sdsds2ww233d0394er",
    name: "St Da Squad",
    price: 450,
    category: "beer",
    description: "test",
    image: "https://freepngimg.com/thumb/bottle/67-beer-bottle-png-image.png",
    rating: 4,
    color: "green-600",
    metaData: [{ volume: "100" }, { alcohol: 8.5 }],
    inStock: true,
  },
  {
    id: "sdsds2ww233d0394sder",
    name: "St Da Squad",
    price: 450,
    category: "rum",
    description: "test",
    image: "https://freepngimg.com/thumb/bottle/67-beer-bottle-png-image.png",
    rating: 4,
    color: "green-600",
    metaData: [{ volume: "100" }, { alcohol: 8.5 }],
    inStock: true,
  },
  {
    id: "sdsdsdwwedr",
    name: "Lanson",
    price: 150,
    category: "whisky",
    description: "test",
    image:
      "https://th.bing.com/th/id/R.1ad7e1fe51c6e7960f123d7a337a45b3?rik=JUE1%2fQ6XkGbH6A&riu=http%3a%2f%2fassets.stickpng.com%2fimages%2f585e7378cb11b227491c344b.png&ehk=80NMIQ%2frDLPiN2UR3rl8MutvpF43GGZ4tTaCbTjFbsY%3d&risl=&pid=ImgRaw&r=0",
    rating: 4,
    color: "green-600",
    metaData: [{ volume: "100" }, { alcohol: 8.5 }],
    inStock: true,
  },
  {
    id: "233ww3",
    name: "San Miguel",
    price: 150,
    category: "wine",
    description: "test",
    image: "https://webstockreview.net/images/beer-bottle-png-9.png",
    rating: 4,
    color: "orange-500",
    metaData: [{ volume: "100" }, { alcohol: 8.5 }],
    inStock: true,
  },
  {
    id: "2333",
    name: "San Miguel",
    price: 150,
    category: "beer",
    description: "test",
    image: "https://webstockreview.net/images/beer-bottle-png-9.png",
    rating: 4,
    color: "orange-500",
    metaData: [{ volume: "100" }, { alcohol: "8.5%" }],
    inStock: true,
  },
  {
    id: "23323333",
    name: "Malboro",
    price: 150,
    category: "cigarettes",
    description: "test",
    image:
      "https://i.pinimg.com/originals/2b/7a/20/2b7a20687bf7bbc12b7f8532d0db5930.png",
    rating: 4,
    color: "orange-500",
    metaData: [{ quantity: "1 PACK", size: "12" }],
    inStock: true,
  },
  {
    id: "2332333ksldsddd3",
    name: "Malboro",
    price: 150,
    category: "cigarettes",
    description: "test",
    image:
      "https://i.pinimg.com/originals/2b/7a/20/2b7a20687bf7bbc12b7f8532d0db5930.png",
    rating: 4,
    color: "orange-500",
    metaData: [{ quantity: "1 PACK", size: "12" }],
    inStock: false,
  },
];
